feat-mailer: Added Mailer Plugin Conversion
drone/go-convert pull request #246
Opened 2024-11-16 19:46 UTC by vanisrikanithi

Mailer go-conversion:
Added "Mailer" support to go-convert specific to jenkins migration.

Mailer Jenkins Trace:
[Mailer_Trace.json](https://github.com/user-attachments/files/17787751/Mailer_Trace.json)

go run main.go jenkinsjson --downgrade ~/go/Mailer_Trace.json

Mailer harness pipeline step:
```
- step:
    identifier: mail0fb620
    name: Mailer
    spec:
      image: plugins/email
      settings:
        body:
          "\n                    Build Status: FAILURE\n                    Check
          console output at: http://localhost:8080/job/Mail_Pipeline/15/console\n
          \                   "

        from.address: <from_address>
        host: smtp.gmail.com
        password: <password>
        port: "587"
        recipients: test.user@testmail.com
        subject: "Jenkins Build - Mail_Pipeline #15"
        username: <username>
    timeout: ""
    type: Plugin
```

2024-11-16 19:47 UTC, vanisrikanithi commented
@Ompragash Added the Mailer support to go-convert, Could you please review it and confirm the changes?

2024-11-19 03:27 UTC, vanisrikanithi commented
Hello @Ompragash,
Could you please review the mailer conversion and provide your review comments if there are any?

Thank you.

2024-11-19 16:14 UTC, Ompragash requested changes

2024-11-19 16:14 UTC, Ompragash commented on convert/jenkinsjson/json/mailer.go
> +				"from.address": "<from_address>",
update the values with `<+input>` wherever needed and remove the hardcoded values

2024-11-19 16:14 UTC, Ompragash commented on convert/jenkinsjson/json/mailer_test.go
> +				"username":     string("<username>"),
once the `ConvertMailer` func is updated, then accordingly update the test based on the trace

2024-11-19 16:14 UTC, Ompragash commented on samples/jenkins/Jenkinsfile
> +                """
please ensure, working sample is added to the sample Jenkinsfile

2024-11-19 23:40 UTC, vanisrikanithi commented
@Ompragash Addressed all the above review comments, could you please check and confirm once?

Thank you.

2024-11-21 15:19 UTC, vanisrikanithi commented
@Ompragash Could you please review the changes made and confirm?

Thanks.

2024-11-21 16:24 UTC, Ompragash approved these changes

2024-11-21 16:24 UTC, merged