feat-sonarqube: Added sonar quality gateway conversion
drone/go-convert pull request #257
Opened 2024-11-26 21:52 UTC by vanisrikanithi

Sonar Quality Gate go-conversion:
Added "Sonar Quality Gate" support to go-convert specific to jenkins migration.

Sonar Quality Gate Jenkins Trace:
[vani_sonar_Trace.json](https://github.com/user-attachments/files/17926111/vani_sonar_Trace.json)

go run main.go jenkinsjson --downgrade ~/go/vani_sonar_Trace.json

Sonar Quality Gate Harness test pipeline [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Sonarqube/deployments/MtoXJuhmQ3aI2M_1KDesyw/pipeline?storeType=INLINE).

Sonar Quality Gate harness pipeline step:
```
- step:
    identifier: waitforqualitygate6278c9
    name: Sonarqube_Quality_Gate
    spec:
      image: 'plugins/sonarqube-scanner:v2.4.2'
      settings:
        scm_disabled: 'false'
        skip_scan: 'false'
        sonar_host: <+input>
        sonar_key: <+input>
        sonar_name: <+input>
        sonar_organization: <+input>
        sonar_quality_enabled: 'true'
        sonar_qualitygate: OK
        sonar_token: <+input>
        sources: .
        timeout: '300'
    timeout: ''
    type: Plugin
```

2024-11-26 21:53 UTC, vanisrikanithi commented
Hello @Ompragash,

Could you please review the PR for sonar quality gate conversion and provide your comments on that?

Thank you.

2024-12-04 17:19 UTC, Ompragash requested changes
Tests failed with below as the test files related to existing implementation of withSonarQubeEnv is removed
```
--- FAIL: TestConvertSonarqube (0.00s)
    convert_test.go:275: failed to read JSON file: open /drone/src/convert/jenkinsjson/convertTestFiles/sonarqube/sonarqubeSnippet.json: no such file or directory
FAIL
```

2024-12-05 14:29 UTC, Ompragash approved these changes

2024-12-05 14:29 UTC, Ompragash commented on convert/jenkinsjson/json/sonarQualityGate.go
> +			Image: "plugins/sonarqube-scanner:v2.4.2",
```suggestion
			Image: "plugins/sonarqube-scanner:latest",
```

2024-12-05 14:29 UTC, Ompragash commented on convert/jenkinsjson/json/sonarQualityGate_test.go
> +			Image: "plugins/sonarqube-scanner:v2.4.2",
```suggestion
			Image: "plugins/sonarqube-scanner:latest",
```

2024-12-05 14:29 UTC, Ompragash commented on convert/jenkinsjson/convertTestFiles/sonarQualityGate/sonarQuanlityGate.yaml
> +      image: 'plugins/sonarqube-scanner:v2.4.2'
```suggestion
      image: 'plugins/sonarqube-scanner:latest'
```

2024-12-05 14:29 UTC, Ompragash approved these changes

2024-12-05 15:00 UTC, merged