Feat ansible playbook: Added Ansible Playbook Conversion step
drone/go-convert pull request #262
Opened 2024-12-03 17:35 UTC by vanisrikanithi

Ansible Playbook go-conversion:
Added "Ansible Playbook " support to go-convert specific to jenkins migration.

Ansible Playbook Jenkins Trace:
[vani_ansible.json](https://github.com/user-attachments/files/17996834/vani_ansible.json)

go run main.go jenkinsjson --downgrade ~/go/vani_ansible.json

Harness Test Pipeline [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/VaniAnsibleTest/deployments/glFIXmDXQ0Gg6l9Dqi1-uQ/pipeline?storeType=INLINE).

Ansible Playbook step:
```
- step:
    identifier: ansibleplaybookb2fcf1
    name: Ansible_Playbook
    spec:
      image: plugins/ansible
      settings:
        become: "true"
        become_user: root
        check: "false"
        extra_vars: var2=value2,var1=value1
        forks: "5"
        inventory: inventory.ini
        limit: localhost
        list_hosts: ""
        playbook: example-playbook.yml
        skip_tags: debug
        start_at_task: ""
        tags: setup,deploy
        vault_id: ""
        vault_password: <secrets.getValue('vault-password')>
    timeout: ""
    type: Plugin

```

2024-12-03 17:36 UTC, vanisrikanithi commented
@Ompragash, Added a Ansible Playbook Conversion step. Could you please check and provide your comments on this PR?

2024-12-04 17:38 UTC, Ompragash requested changes

2024-12-04 17:38 UTC, Ompragash commented on convert/jenkinsjson/json/ansible.go
> +				"vault_password": "<secrets.getValue('vault-password')>",
`vault_password` is optional and should be called only when seen in the trace - this can go under if statement

2025-01-11 05:35 UTC, hemanthmantri commented
@Ompragash @vanisrikanithi :  Is there anything blocking from making progress on this PR?

2025-01-11 05:36 UTC, hemanthmantri commented
@vanisrikanithi Please include the jira ticket ID in the PR title. Please see: https://github.com/drone/go-convert/pull/274 for reference.

2025-01-12 23:00 UTC, closed without merging